noir-lang/acvm-backend-barretenberg

Cargo.toml
src/acvm_interop/mod.rs
src/acvm_interop/proof_system.rs
src/acvm_interop/pwg/merkle.rs
src/acvm_interop/smart_contract.rs
src/barretenberg_wasm/mod.rs
src/serialiser/mod.rs

Dummy proof and verification for now, circuit and witnesses are serialized to disk so that noir-cli-js will be able to use them to generate the proof.

wasm-base feature to have a native noir backend using the WASM barretenberg 

---

Cargo.lock
Cargo.toml

Changes the proving system dependency to use the newer aztec-connect codebase, instead of the old AztecProtocol/barretenberg

Use aztec-connect version of barretenberg

---

Cargo.toml

Point to the latest aztec-connect commit [582b343b](https://github.com/noir-lang/aztec-connect/commit/582b34ea4ec0bb55a1369d8cb8b8ae1e6f009f1a) that merged the PR [_Fix Compiling from nargo on M2 Mac_](https://github.com/noir-lang/aztec-connect/pull/1).

Update `barretenberg_wrapper` Commit

---

Cargo.lock
common/Cargo.toml

This replaces the `acvm` dependency from the noir repo and with the `acvm` from its standalone repo.
This dependency currently can't be downloaded on a fresh install because the `7460dda929130589bccfd6619f9409834b72a135` commit was part of https://github.com/noir-lang/noir/pull/551 but that branch was deleted—so a fresh clone of `noir-lang/noir` doesn't include the commit.
@vezenovm suggested that we point to the https://github.com/noir-lang/acvm repository now that it has been split from the noir repo; however, there has been *a lot* of changes to the project. I've pinned the project to the same commit as the final, shared commit: https://github.com/noir-lang/noir/commit/c15c9dabc7d402b54ea290d2b6e0572f513865bd

Use published acvm v0.1.0

---

barretenberg_static_lib/src/acvm_interop/proof_system.rs
barretenberg_static_lib/src/acvm_interop/pwg/gadget_call.rs
barretenberg_static_lib/src/acvm_interop/pwg/merkle.rs
barretenberg_static_lib/src/composer.rs
barretenberg_wasm/src/acvm_interop/pwg/merkle.rs

This just removes unused imports and uses slices instead of vecs where they're not needed.

Fix clippy warnings

---

barretenberg_static_lib/Cargo.lock
barretenberg_static_lib/Cargo.toml

This updates the `barretenberg_wrapper` crate from noir-lang/aztec-connect to the latest commit. This is necessary to build successfully on Mac with homebrew in a non-default location.
We may want to wait to update this until we land https://github.com/noir-lang/aztec-connect/pull/8 so we have the Clang changes for Linux ARM

Update barretenberg_wrapper to use branch

---

barretenberg_static_lib/Cargo.toml

This dependency seems to be leftover from before the `aztec_backend_wasm` was split out into its own package. Should be good to remove from here.

Remove console_error_panic_hook from barretenberg_static_lib

---

Cargo.lock
barretenberg_static_lib/Cargo.toml
common/Cargo.toml

The openssl crate makes it difficult to cross-compile our dependencies, so this swaps the TLS implementation to [rustls](https://github.com/rustls/rustls).
This is a dependency that doesn't require openssl to exist on a system, and helps with cross-compilation. I found out that they don't have complete support (e.g. RISC-V is unsupported) but they seem to support all the platforms we really care about.

feat: Leverage rustls when using downloader crate

---

Cargo.lock
barretenberg_static_lib/src/acvm_interop/proof_system.rs
barretenberg_static_lib/src/acvm_interop/pwg.rs
barretenberg_wasm/src/acvm_interop/proof_system.rs
barretenberg_wasm/src/acvm_interop/pwg.rs
common/Cargo.toml

Update aztec_backend to reflect the new acvm `0.4.1` release. This will let us update the commit in this PR under the main Noir repo (https://github.com/noir-lang/noir/pull/630) enabling print line statements. 
I use the `#[allow(unused_variables)]` for the unused acvm interface functions. These functions are still a work in progress, but it would be good to update the aztec backend to get the log statements PR in on the main Noir repo.

chore(acvm): Update aztec_backend to reflect acvm 0.4.1

---

.github/workflows/rust.yml

This pulls across the change from https://github.com/noir-lang/noir/pull/806 so we can use it in this repo as well.

feat(ci): add concurrency group for rust workflow

---

Cargo.lock
barretenberg_static_lib/src/acvm_interop/proof_system.rs
barretenberg_static_lib/src/acvm_interop/smart_contract.rs
barretenberg_wasm/src/acvm_interop/proof_system.rs
barretenberg_wasm/src/acvm_interop/smart_contract.rs
common/Cargo.toml
common/src/gadget_caller.rs
common/src/serialiser.rs

Updates to use the new ACVM 0.5.0 interface (references for circuits + keys, maps for public inputs when verifying).
Support for `eth_contract_from_vk` and new keccak opcode are left as `todo!()`

feat!: update to acvm v0.5.0

---

aztec_backend_wasm/src/lib.rs

We're referring to the old "gates" field on `Circuit` rather than the new "opcodes" field. This should be picked up be type checking so we should also investigate why this doesn't error.

fix: rename gates to opcodes

---

aztec_backend_wasm/src/lib.rs
barretenberg_js/src/acvm_interop/proof_system.rs
barretenberg_static_lib/src/acvm_interop/pwg.rs
barretenberg_static_lib/src/acvm_interop/pwg/gadget_call.rs
barretenberg_static_lib/src/composer.rs
barretenberg_static_lib/src/integration.rs
barretenberg_wasm/src/acvm_interop/proof_system.rs
barretenberg_wasm/src/acvm_interop/pwg.rs
barretenberg_wasm/src/acvm_interop/pwg/gadget_call.rs
barretenberg_wasm/src/acvm_interop/pwg/merkle.rs
common/src/barretenberg_structures.rs
common/src/gadget_caller.rs
common/src/serialiser.rs
cspell.json

This applies all of the non-breaking spell check fixes. We also have other changes to make but they either affect:
1. The verifier smart contract (non-breaking)
2. Breaking spelling changes which affect the interface e.g. `serialise_acir_to_barrtenberg_circuit`

chore: apply non-breaking spellcheck fixes

---

barretenberg_js/src/acvm_interop/proof_system.rs
barretenberg_static_lib/src/acvm_interop/proof_system.rs
barretenberg_static_lib/src/composer.rs
barretenberg_wasm/src/acvm_interop/proof_system.rs
barretenberg_wasm/src/composer.rs
common/src/lib.rs
common/src/proof.rs

We never pass `None` as the public inputs, it's always `Some` empty `Assignments` when we have no public inputs, I've then removed this extra layer.
I've also pulled all the code related to prepending and stripping public inputs to/from proofs into `common` so all methods can reuse it.

chore: simplifications and deduplications of shared code

---

barretenberg_static_lib/src/composer.rs
barretenberg_wasm/src/acvm_interop/proof_system.rs
barretenberg_wasm/src/composer.rs

Looks like #66 missed a couple of instances of the logic to prepend the public inputs onto the proof.

chore: deduplicate logic for prepending public inputs 

---

common/Cargo.toml

Looks like I misread the docs when making #73, rather than marking `common` as private we should mark it as non-publishable.

chore: replace incorrect flag to mark `common` private

---

aztec_backend_wasm/src/lib.rs
barretenberg_static_lib/src/acvm_interop/proof_system.rs
barretenberg_wasm/src/acvm_interop/proof_system.rs
common/src/proof.rs

We've currently got several different implementations of flattening a witness map into a vector in various crates (including one incorrect one in `aztec_backend_wasm`).
This PR pulls out this logic into a function in `common` which can be reused.
I've avoided making this a method on `Assignments` as this implementation is specific to proving whereas we use `Assignments` for both proving and verifying.

chore: factor out function to flatten witness map

---

common/src/contract/cryptography/polynomial_eval.rs

Small fix that removes the Solidity "stack too deep" compiler error when compiling the verifier contract with the Solidity optimiser turned off.

verifier should compile without needing optimizer turned on

---

Cargo.lock
common/Cargo.toml
common/src/serializer.rs

This PR updates us to use the new version of the ACVM crate. The only change which is relevant is the addition of the `Block` opcode.
@guipublic It seems to me that we can just handle this similarly to directives when serializing for BB. Let me know if we should handle this differently.

chore: bump to ACVM 0.6.0

---

barretenberg_wasm/src/composer.rs
barretenberg_wasm/src/pedersen.rs
barretenberg_wasm/src/scalar_mul.rs
barretenberg_wasm/src/schnorr.rs

This adds additional testing to `barretenberg_wasm`. While working on #84, @vezenovm has to link everything into Noir to run tests to find problems in the wasm. This adds a base layer of tests so we hopefully catch some things before needing to link into Noir.

chore: Duplicate static_lib tests into wasm to verify same functionality

---

common/src/crs.rs

This change allows us to override the transcript location using the `BARRETENBERG_TRANSCRIPT` environment variable. This is necessary because Nix builds everything in a read-only sandbox where the download would fail. We can instead specify it as a dependency of building in nix and make the path available through this env var.

feat: allow overriding transcript location with BARRETENBERG_TRANSCRIPT env var

---

Cargo.lock
barretenberg_static_lib/Cargo.toml
barretenberg_static_lib/src/acvm_interop/pwg/merkle.rs

The title basically describes the entire contents of the PR. These are the same tests that exist in the `barretenberg_wasm` crate. I also added a test called `simple_shield` that mocks the functionality of our integration test from nargo. This lets us easily print debug output from this test if needed when pedersen changes (this is rare but can happen).

chore: Add merkle tree tests to static lib

---

README.md
cspell.json

We expect people to build with Nix, so this adds quick guidelines on building the project to a README.

chore: add readme describing how to build from source

---

Cargo.lock
barretenberg_static_lib/Cargo.toml
flake.lock

This updates bb-sys to 0.1.1 which resolves a breaking barretenberg change and updates our nix lockfile to use an updated bb commit.

fix: update to bb-sys 0.1.1 and update bb in lockfile

---

Cargo.lock
barretenberg_static_lib/src/crs.rs
common/Cargo.toml
common/src/crs.rs
cspell.json

This PR replaces `downloader` with `reqwest`
This results in the progress bar being displayed as below:
```
// Downloader
Downloading the Ignite SRS (340MB)
[00:00:17] ######################################## 322560348/322560348 
Downloaded the SRS successfully!
Time Elapsed: 17 seconds
// Reqwest
Downloading the Ignite SRS (340MB)
[00:00:17] ######################################## 307.62 MiB/307.62 MiB Downloaded the SRS successfully!
SRS is located at: "/home/tom/.nargo/backends/acvm-backend-barretenberg/transcript00.dat"
```
The "Downloaded the SRS successfully!" message only appears on completion of the download. I've removed the "Time Elapsed" line as this is displayed in the progress bar.
Resolves #47

feat: replace `downloader` dependency with `reqwest`

---

barretenberg_static_lib/src/composer.rs
barretenberg_wasm/src/composer.rs
barretenberg_wasm/src/pedersen.rs
common/src/barretenberg_structures.rs
common/src/proof.rs

This change removes the `pub Vec<Scalar>` internals of the `Assignments` type. It then adds some utilities that are needed to stop reaching into the internals. I also cleaned up the tests by using `into()`
This will help us add wasm_bindgen to it in the future.

fix!: avoid exposing internals of Assignments type

---

barretenberg_wasm/src/composer.rs

It seems like someone accidentally reimplemented `Barretenberg.call` when writing these functions. I've then replaced it with just using the proper method.

fix: use `Barretenberg.call` to query circuit size from wasm

---

barretenberg_static_lib/src/acvm_interop/pwg/black_box_functions.rs
barretenberg_static_lib/src/schnorr.rs
barretenberg_wasm/src/acvm_interop/pwg/black_box_functions.rs
barretenberg_wasm/src/schnorr.rs
common/src/black_box_functions.rs

This PR simplifies the `verify_signature` function so that it returns a boolean for whether the signature was valid or not rather than the field element which will be assigned to a witness as a result of this.
This translation is now done in `solve_black_box_func_call`.

feat!: return boolean rather than `FieldElement` from `verify_signature`

---

barretenberg_static_lib/src/acvm_interop/smart_contract.rs
barretenberg_static_lib/src/composer.rs
barretenberg_wasm/src/acvm_interop/smart_contract.rs
barretenberg_wasm/src/composer.rs
common/src/barretenberg_structures.rs

This builds upon #118 and hides all fields on the ConstraintSystem struct. It then implements an Builder-like pattern on the ConstraintSystem for building them up in tests (note that this is only ever used in tests and in normal use these are constructed via `From<&Circuit>`)
I opted away from an entirely new struct for the builder pattern because we use vecs for everything and they can be defaulted to empty vecs. Marking as a draft so we can decide if this is good enough.

feat!: Implement pseudo-builder pattern for ConstraintSystem & hide struct fields

---

barretenberg_static_lib/src/composer.rs
common/src/barretenberg_structures.rs

This is essentially a copy of the `acir_format` logic constraint test from barretenberg. I am going to be using the logic constraint system in some other tests utilizing recursion so I am adding here separately as to not have PR creep.

chore: Add logic constraint test from C++ acir_format tests

---

barretenberg_static_lib/src/acvm_interop/proof_system.rs
barretenberg_wasm/src/acvm_interop/proof_system.rs

This function has been bugging me so I've partitioned and grouped the arms depending on whether we support the BB function or not

chore: cleaner implementation of `black_box_function_supported`

---

.github/workflows/test.yml
common/src/lib.rs
flake.nix

This caches the "cargoArtifacts" derivation from Nix via GitHub Actions Cache. That includes all cargo dependencies as produced by `craneLib.buildDepsOnly`. We then import the deps into Nix if the cache exists.
This reduced the CI run on ubuntu down to 7 minutes, roughly 5-6 of it being the actual test run.

chore(ci): Cache cargo dependencies between runs

---

common/src/black_box_functions.rs

This comment was from a time when each backend would define how it would do particular operations. Now, we are of the opinion that this should be standardized by ACIR

chore: remove outdated comment

---

acvm_backend_barretenberg/src/acvm_interop/smart_contract.rs
acvm_backend_barretenberg/src/composer.rs
common/src/barretenberg_structures.rs

I've removed some unused methods, derived default rather than defining it in terms of `new()` and replaced the usage of `Scalar` renaming of `FieldElement`.

chore: miscellaneous refactoring of `barretenberg_structures`

---

Cargo.lock
Cargo.toml
flake.lock
src/acvm_interop/proof_system.rs
src/acvm_interop/pwg.rs
src/barretenberg_structures.rs
src/composer.rs

Blocked by https://github.com/AztecProtocol/barretenberg/pull/385 and https://github.com/noir-lang/acvm/pull/204

feat!: migrate to ACVM 0.10.3

---

src/acvm_interop/smart_contract.rs
src/composer.rs
src/lib.rs
src/pedersen.rs
src/scalar_mul.rs
src/schnorr.rs

Addresses review comment https://github.com/noir-lang/aztec_backend/pull/151#discussion_r1185926029.
A lot of our type issues were due to `slice_memory` returning a `&[u8]` whereas we want a fixed length array. This leads to us having more information than the compiler and so need to `try_into().unwrap()` in a lot of places.
I've fixed this by giving the compiler more hints about what we want returned from `slice_memory`, it's now generic with a const parameter `SIZE` and will return a `[u8; SIZE]` array. We no longer pass a length argument but will often have to provide a type hint when calling the function.
This isn't always usable for all situations where we need to read from memory (as we don't always know the length of the array at compile time. I've then added …

chore: Enforce proper conversion of memory into fixed length array

---

src/composer.rs

It's not clear to me on why we "forget" the CRS, PK, constraint systems and witness. I remember that previously Barretenberg would have some singleton instance of the proving key, etc. which would make some sense. We don't do this anymore and in any case, we pass in new values for each of these on every call so I don't see any reason to not to free these resources.

chore: remove usage of `std::mem::forget`

---

Cargo.lock
Cargo.toml
cspell.json
flake.lock
src/acvm_interop/proof_system.rs
src/acvm_interop/pwg.rs
src/acvm_interop/pwg/merkle.rs
src/acvm_interop/smart_contract.rs
src/barretenberg_structures.rs
src/composer.rs
src/lib.rs
src/merkle.rs
src/pedersen.rs
src/pippenger.rs
src/scalar_mul.rs
src/schnorr.rs

This reworks the backend to leverage the changes for fallible functions. It introduces an error enum with admittedly bad variant names and uses them to map error cases throughout the codebase so panic and/or unwrap isn't used to handle most values.
~~There are still some TODOs to cleanup even more `unwrap` cases and it relies on something like https://github.com/noir-lang/acvm/pull/251, but this should be a solid skeleton for how a backend can surface errors to nargo.~~
Closes #159

feat!: Update to ACVM v0.11.0

---

.github/workflows/publish.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

Closes #107 
This adds the release-please, publish, and PR title checking workflows to the project. We'll need a publish token to make the publish workflow actually publish.
Merging this PR should coincide with renaming the repository and creating an archived mirror as "aztec_backend". We don't want to archive this repo because we can't transfer PRs.

chore: Add release-please and publish workflows to project

---

.github/workflows/publish.yml
.github/workflows/release.yml

This updates the tokens in the workflows.

chore(ci): Update tokens

---

Cargo.lock
Cargo.toml
src/acvm_interop/pwg.rs
src/barretenberg_structures.rs

related to https://github.com/noir-lang/acvm/pull/269

feat!: update to acvm with non-homogeneous bb calls

---

Cargo.toml
README.md
flake.nix

This adds a description to the crate so it can be published. Published of 0.1.0 failed at https://github.com/noir-lang/acvm-backend-barretenberg/actions/runs/4943022200/jobs/8837108338

fix: Add description so crate can be published

---

Cargo.lock
Cargo.toml
src/acvm_interop/smart_contract.rs
src/composer.rs
src/crs.rs

This switches to using the `tokio::test` macro to use tokio async test runner for any functions that rely on CRS and other async functions in the future.
Removing the tokio calls from functions will allow us to swap in other test runners that support async functions, such as wasm-bindgen-test for browser tests.
I also made the CRS pippenger test run in all targets by relying on the `get_pippenger` abstraction.

chore: Switch to tokio test macro for async function

---

Cargo.lock
Cargo.toml
cspell.json
src/acvm_interop/pwg/merkle.rs
src/composer.rs
src/crs.rs
src/merkle.rs

This removes `sled` and `tempfile` from the merkle tests. By removing these file-based dependencies from the test infrastructure, we'll need less separation between between wasm32 target tests and native tests.
I'm not sure why the file-based dependencies were used, but it seems that the tests can be done with in-memory BTreeMaps.
Tests are passing, but need a review to make sure I didn't mess something up which makes them always pass 😛

chore: Remove `sled` & `tempfile` dev-dependencies

---

Cargo.lock
Cargo.toml
cspell.json
src/crs.rs

This removes the streaming download of the CRS bytes and removes the indicator about how much is downloaded.
Since we are now adjusting our download on circuit size (and growing the CRS as a circuit grows), the backend will no longer be downloading 307mb in one single download. This was making the indicator go from 0 to complete instantly, which looks strange.
Additionally, this sets us up to use the same download function both natively and in JS.

chore: Remove streaming CRS download & indicator

---

Cargo.lock
Cargo.toml
src/barretenberg_structures.rs

This adds serde to all of the ConstraintSystem types. These types being serializable is necessary for running JS tests in a worker thread.

feat: Add serde to `ConstraintSystem` types

---

src/lib.rs

This is a temporary fix until we can get wasmer 3.x and then we can join the implementations like #197

fix: Add or cleanup implementations for JS target

---

Cargo.lock
Cargo.toml
src/acvm_interop/common_reference_string.rs
src/composer.rs

As noted in https://github.com/noir-lang/acvm/pull/292, the JS implementation does not implement the `Send` trait, so this allows our async code to not implement.

fix: Allow async functions without send on async trait

---

Cargo.toml
src/lib.rs

Depends on #198 and #199 
This reorganizes the `Cargo.toml` to tie features to their dependencies and just enables the dependency based on the `native` or `wasm` feature of the crate. It also removes the `js` feature and instead relies on the wasm32 `target_arch`.

feat!: Replace `js` feature with `wasm32` target

---

flake.lock
src/composer.rs
src/merkle.rs
src/pedersen.rs

Pedersen implementation changed in https://github.com/AztecProtocol/barretenberg/pull/414/files#diff-3efc25f3b79f11be68c59e48ae56e83dbd6f38a4c0505e2e3f5ddb3297b7c520
Pointing barretenberg to this commit https://github.com/AztecProtocol/barretenberg/commit/ad282152836f5e3a5c8f34256b29bdea9d16b854 and updated the pedersen tests
Before:
```
```
After:
```
```

fix!: update pedersen hashes for new implementation

---

flake.lock
src/barretenberg_structures.rs

Updates BB to the keccakvar commit and updates the serialization with the keccakvar constraints (unused for now).
Replaces https://github.com/noir-lang/acvm-backend-barretenberg/pull/211

feat!: added keccakvar constraints

---

Cargo.toml

In the [Noir PR](https://github.com/noir-lang/noir/pull/1393) that integrates acvm-0.13.0 updates there was a blocker where `acvm-backend-barretenberg` was not being found. 
I followed the hack mentioned in this issue (https://github.com/rust-lang/cargo/issues/4881). That includes an extra `crate-type`. However, I this most likely blows up the size of the binary that is created. And I noticed that cargo added a flag a few months ago to specify the crate type (https://github.com/rust-lang/cargo/issues/10083). Should we update our manifest and flake on the Noir repo to handle this @phated ?
I pushed this PR to test the Noir CI with the new dep: [acvm-0.13.0-dbg](https://github.com/noir-lang/noir/tree/acvm-0.13.0-dbg). I will push this branch as a PR on the Noir repo once the final CI passes …

fix: Add `lib` crate-type to build 

---

Cargo.lock
Cargo.toml
src/acvm_interop/pwg.rs

This PR updates to target ACVM 0.15.0. I've marked this PR as breaking as it any consumer of this package will need to opt into a breaking change of ACVM.

feat!: Update to target ACVM 0.15.0

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml

Resolves 
It seems that `noir_wasm` causes dependency conflicts within this crate when we enable the wasm backend. Removing the wasm32 target from this package allows us to build with the wasm backend again.
Since we aren't going to use this package in the browser, we can just remove this instead of a larger refactoring.

fix: Remove wasm32 target

---

flake.lock
src/composer.rs

This PR updates to use the latest commit on https://github.com/AztecProtocol/barretenberg/pull/499 to show how it breaks the `test_memory_constraints` test. We should fix this before proceeding with #221

chore: update to latest barretenberg noir master commit

---

Cargo.lock
Cargo.toml
flake.lock
src/acvm_interop/proof_system.rs
src/acvm_interop/pwg.rs
src/barretenberg_structures.rs
src/composer.rs

feat!: Update to ACVM 0.16.0 

---

Cargo.lock
Cargo.toml
flake.lock
src/acvm_interop/proof_system.rs
src/barretenberg_structures.rs
src/composer.rs

**TODO**
- waiting on fix for block constraints test
Adds bindings to enable secp256r1 verification in noir
Resolves

feat(bberg)!: add secp256r1 builtin to barretenberg

---

Cargo.lock
Cargo.toml
src/acvm_interop/proof_system.rs
src/barretenberg_structures.rs

Add support for new ACIR opcodes for atomic memory operation. They allow ACVM to perform stepwise solving for dynamic memory.
Resolves 
The backend simply collect these opcode into a block constraint.

feat: add support for atomic memory opcodes

---

Cargo.lock
Cargo.toml
src/lib.rs

Prerequisite for https://github.com/noir-lang/noir/issues/2235
This PR migrates us to `wasmer` 3.3.0 as using https://github.com/noir-lang/acvm/pull/494 while using `wasmer` 2.3.0 fails to compile.
As part of this I've removed all of the code which handles the wasm32 target as this crate has never worked for that target and will be retired soon anyway.

feat: Migrate to `wasmer` 3.3.0

---

.github/workflows/test.yml

Resolves 
This PR updates how we handle caches to be closer to how we do it in the main repository, cache entries are created even if the tests fail.
A timeout of 30 minutes is also added.

chore(ci): create cache entries even if tests fail
